syntax off
execute pathogen#infect()

set nocompatible
set backspace=indent,eol,start
set nobackup		" do not keep a backup file, use versions instead
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
let highlight_function_name = 1
syntax on
set hlsearch
filetype plugin on
filetype plugin indent on
set autoindent		" always set autoindenting on
set showmatch showmode
set ignorecase
set expandtab
set shiftwidth=4
set report=0
set smartindent
set tabstop=4
set laststatus=2
set guifont=Andale\ Mono\ 12
set guioptions-=T
":runtime /usr/share/vim/vim62/plugin/taglist.vim
"set Tlist_Ctags_Cmd /usr/bin/ctags
set encoding=utf-8
set fileencoding=utf-8
set autowrite
:colorscheme peachpuff

set foldmethod=marker
set foldnestmax=10
set foldenable
set foldlevel=0

set statusline=%<%f%h%m%r\ %b\ %{&encoding}\ \ %l,%c%V\ %P

let g:miniBufExplModSelTarget = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1 

:nnoremap <F1> :bp<CR>
:nnoremap <F2> :bnext<CR>


" F8 - "make"
map <F8> :make<cr>
vmap <F8> <esc>:make<cr>i
imap <F8> <esc>:make<cr>i

set showfulltag

let g:ycm_confirm_extra_conf = 0
let g:ycm_register_as_syntastic_checker = 1
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_add_preview_to_completeopt = 0
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_key_invoke_completion = '<C-Space>'
set completeopt-=preview


autocmd BufRead *.as set filetype=actionscript
