syntax off
execute pathogen#infect()

set nocompatible
set backspace=indent,eol,start
set nobackup		" do not keep a backup file, use versions instead
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
let highlight_function_name = 1
syntax on
set hlsearch
filetype plugin on
filetype plugin indent on
set autoindent		" always set autoindenting on
set showmatch showmode
set ignorecase
set expandtab
set shiftwidth=4
set report=0
set smartindent
set tabstop=4
set laststatus=2
set guifont=Andale\ Mono\ 12
set guioptions-=T
:runtime /usr/share/vim/vim62/plugin/taglist.vim
"set Tlist_Ctags_Cmd /usr/bin/ctags
set encoding=utf-8
set fileencoding=utf-8
set autowrite
:colorscheme peachpuff

set statusline=%<%f%h%m%r\ %b\ %{&encoding}\ \ %l,%c%V\ %P

let g:miniBufExplModSelTarget = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1 

let Tlist_Use_Right_Window = 1
let Tlist_WinWidth = 10
let Tlist_Show_One_File = 1
"let Tlist_Auto_Open = 1
let Tlist_Compact_Format = 1
let Tlist_Use_SingleClick = 0
let Tlist_Enable_Fold_Column = 0

:nnoremap <F1> :bp<CR>
:nnoremap <F2> :bnext<CR>


" F8 - "make"
map <F8> :make<cr>
vmap <F8> <esc>:make<cr>i
imap <F8> <esc>:make<cr>i

set showfulltag

autocmd BufRead *.as set filetype=actionscript
